name: data-upload-webapp

environment: prod

replicas: 3

image:
  repository: venkatsunilm
  name: data-upload-webapp
  tag: "latest"
  pullPolicy: IfNotPresent

# flask_env: development

# service:
#   type: ClusterIP
#   port: 8000

# ingress:
#   enabled: true
#   annotations: {}
#   hosts:
#     - host: datauploadwebapp.com # Replace with your domain
#       paths:
#         - /
#   tls: []

# resources: {}
